### ISSUE TITLE
请加上requirements.txt

### ISSUE THREAD

**Issue by lanybass** [einsxiao/GlobalVim#1]
wxpython
pyhook3
keyboard
mouse
winshell

**Comment by lanybass** [comment]
另外，win7测试了，表示界面卡卡的

**Comment by lanybass** [comment]
设置GK热键报错，设置界面按任意键都报：
> keyboard error for: 'ascii' codec can't decode byte 0xe5 in position 2: ordinal not in range(128)

**Comment by einsxiao** [comment]
我，好多人担心exe不安全，我就没有发exe了。只在微软商店有放一份过微软审查的版本。
