### ISSUE TITLE
微软应用商城无法下载此应用

### ISSUE THREAD

**Issue by ecjtusbs** [einsxiao/GlobalVim#5]
无法在应用商店购买此应用：提示信息为：
【你可以在 Xbox One 主机上购买。(你所在的地区不支持通过 microsoft.com 购买）】。
请问该如何体验此应用呢？

**Comment by einsxiao** [comment]
> 无法在应用商店购买此应用：提示信息为：
> 【你可以在 Xbox One 主机上购买。(你所在的地区不支持通过 microsoft.com 购买）】。
> 请问该如何体验此应用呢？

微软商店上有按地区划分，可以把系统的地区设置为香港或者大陆，重启之后再尝试。
